inter.base-url=${INTER_BASE_URL:https://cdpj.partners.bancointer.com.br}
inter.certificate-path=${INTER_CERTIFICATE_PATH:}
inter.private-key-path=${INTER_PRIVATE_KEY_PATH:}
inter.certificate-required=${INTER_CERTIFICATE_REQUIRED:true}
