inter.base-url=${INTER_BASE_URL:https://cdpj-sandbox.partners.uatinter.co}
inter.certificate-path=${INTER_CERTIFICATE_PATH:.certs/interapicertificado.crt}
inter.private-key-path=${INTER_PRIVATE_KEY_PATH:.certs/interapi_chave.key}
inter.certificate-required=${INTER_CERTIFICATE_REQUIRED:false}
